### ISSUE TITLE
Feature Request - extract headers for use as a variable

### ISSUE THREAD

**Issue by peterhoeg** [federicotdn/verb#4] opened 2020-01-27 15:54 UTC
One example would be a JWT token that is returned which should be used for future requests. It is of course possible to simply define it as a variable manually with copy/paste but it would be fantastic to have it made possible in a more structured manner.

**Comment by federicotdn** [comment] 2020-01-27 18:23
For the moment, the closest we can get to this is using the `verb-last` variable, which stores the last response. If you include `{{(oref verb-last body)}}` anywhere in your request spec, it'll include the body of that last response. The problem is that then the last response will be overwritten with a new one, that doesn't include the JWT token.

I'll look into ways particular responses can be saved permanently and re-used.

**Comment by federicotdn** [comment] 2020-01-27 21:59
@peterhoeg please check if this is useful! https://github.com/federicotdn/verb#storing-responses-by-key

**Comment by federicotdn** [comment] 2020-02-04 22:52
Closing as this is implemented:

First, select a response:
- Use `verb-last` to get the last response
- Use `(verb-stored-response "xyz")` to get a stored response by key

Then, read from it (for example using `verb-last`):
- Use `(verb-json-get (oref verb-last body) "id")` to extract contents from the body
- Use `(verb-headers-get (oref verb-last headers) "Location")` to extract contents from the headers

**Closed by federicotdn** 2020-02-04 22:52 UTC
Labels: enhancement

**Comment by peterhoeg** [comment] 2020-02-05 04:58
Thanks for doing this - I haven't had the time to try it out.
